[id="bananaChap2"]
= Chapter 2

NEW TEXT FOR CHAP 2

This is chapter 2 text. Chapter 2 has a subtitle.

xref:bananaChap1[Id-based to chapter 1.]

xref:chap1.adoc[Here's an xref to chapter 1.]

xref:chap1.adoc#ben-target[Here's a deep xref to chapter 1.]

xref:cool-stuff[This xref keeps you in this document.]

Triangle xrefs:

<<chap1.adoc#,Here's an xref to chapter 1.>>

<<chap1.adoc#ben-target,Here's a deep xref to chapter 1.>>

<<cool-stuff,This xref keeps you in this document.>>

The beginnings - Roadster and private funding

Founded as Tesla Motors, Tesla was incorporated on July 1, 2003 by Martin Eberhard and Marc Tarpenning.[1] The founders were influenced to start the company after General Motors recalled all its EV1 electric cars in 2003 and then destroyed them,[2] and seeing the higher fuel efficiency of battery-electric cars as an opportunity to break the usual correlation between high performance and low fuel economy in automobiles.[3] The AC Propulsion tzero also inspired the company's first vehicle, the Roadster.[4][5]

Ian Wright was the third employee, joining a few months later.[1] The three went looking for venture capital (VC) funding in January 2004[1] and connected with Elon Musk, who contributed US$6.5 million of the initial (Series A) US$7.5 million[6] round of investment in February 2004 and became chairman of the board of directors.[1] Musk then appointed Eberhard as the CEO.[7] J.B. Straubel joined in May 2004[1] as the fifth employee.[8] A lawsuit settlement agreed to by Eberhard and Tesla in September 2009 allows all five (Eberhard, Tarpenning, Wright, Musk and Straubel) to call themselves co-founders.[9]

[[cool-stuff]]
== This is an xref target inside chapter 2.

Musk took an active role within the company and oversaw Roadster product design at a detailed level, but was not deeply involved in day-to-day business operations.[10] Eberhard acknowledged that Musk was the person who insisted from the beginning on a carbon-fiber-reinforced polymer body and that Musk led design of components ranging from the power electronics module to the headlamps and other styling.[11] Musk received the Global Green 2006 product design award for his design of the Tesla Roadster, presented by Mikhail Gorbachev,[12] and he also received the 2007 Index Design award for his design of the Tesla Roadster.[13]
The insignia of Tesla Motors as seen on a Tesla Roadster Sport

From the beginning, Musk consistently maintained that Tesla's long-term strategic goal was to create affordable mass market electric vehicles.[14] Tesla's goal was to start with a premium sports car aimed at early adopters and then moving into more mainstream vehicles, including sedans and affordable compacts.[15]

Musk's Series A investment round in February 2004 included Compass Technology Partners and SDL Ventures, as well as many private investors. In February 2006, Musk led Tesla's Series B US$13 million investment round which added Valor Equity Partners to the funding team.[16] Musk co-led the third, US$40 million round in May 2006 along with Technology Partners. Tesla's third round included investment from prominent entrepreneurs including Google co-founders Sergey Brin & Larry Page, former eBay President Jeff Skoll, Hyatt heir Nicholas J. Pritzker and added the VC firms Draper Fisher Jurvetson, Capricorn Management, and The Bay Area Equity Fund managed by JPMorgan Chase.[17] The fourth round in May 2007 added another US$45 million and brought the total investments to over US$105 million through private financing.[citation needed]

Eberhard served as CEO until he was asked to step down from the position in August 2007 by the board of directors.[18][19][20] Eberhard then took the title of "President of Technology" before ultimately leaving the company in January 2008. Co-founder Marc Tarpenning, who served as the Vice President of Electrical Engineering of the company, also left the company in January 2008.[20][21] In August 2007, Michael Marks was brought in as interim CEO, and in December 2007, Ze'ev Drori became CEO and President.[20] In January 2008, Tesla fired several key personnel who had been involved from the inception after a performance review by the new CEO.[22] According to Musk, Tesla was forced to reduce the company workforce by about 10% to lower its burn rate, which was out of control in 2007.[23] In May 2008, "The Truth About Cars" website launched a "Tesla Death Watch", as Tesla needed another round of financing to survive. In October 2008, Musk succeeded Drori as CEO and fired 25% of Tesla employees.[20] Drori became vice-chairman, but then left the company in December 2008. In December a fifth round of investment turned into debt financing and added another US$40 million, avoiding bankruptcy.[24][25]

By January 2009, Tesla had raised US$187 million and delivered 147 cars. Musk had contributed US$70 million of his own money to the company.[23][26] On May 19, 2009, Germany's Daimler AG, maker of Mercedes-Benz, acquired an equity stake of less than 10% of Tesla for a reported US$50 million.[27] According to Musk, the Daimler investment saved Tesla.[28] In July 2009, Daimler announced that Abu Dhabi's Aabar Investments bought 40% of Daimler's interest in Tesla.[29]
The Tesla obelisk is used to identify the Supercharger network sites in California.
2009 Department of Energy loan

In June 2009 Tesla was approved to receive US$465 million in interest-bearing loans from the United States Department of Energy. The funding, part of the US$8 billion Advanced Technology Vehicles Manufacturing Loan Program, supported engineering and production of the Model S sedan, as well as the development of commercial powertrain technology.[30] The low-interest loan program was created in 2007 during the George W. Bush administration, and is not related to the "bailout" funds that GM and Chrysler received, nor are they related to the 2009 economic stimulus package.[31] Tesla repaid the loan in May 2013, with a US$12 million interest. Tesla was the first car company to have fully repaid the government;[32] Nissan repaid their loan in 2017, Ford expects to repay their loan in 2022, and Fisker went bankrupt and defaulted on their loan.[33]

The company announced in early August 2009 that it had achieved overall corporate profitability for the month of July 2009.[34] The company said it earned approximately US$1 million on revenue of US$20 million. Profitability arose primarily from improved gross margin on the 2010 Roadster, the second iteration of Tesla's award-winning sports car. Tesla, which like all automakers records revenue when products are delivered, shipped a record 109 vehicles in July and reported a surge in new Roadster purchases. In September 2009, Tesla announced a US$82.5 million round to accelerate Tesla's retail expansion.[35] Daimler participated in the round to maintain equity ownership from its initial investment.[35]
Lotus supply of Roadster parts

Tesla Motors signed a production contract on July 11, 2005, with Group Lotus to produce "gliders" (complete cars minus powertrain).[36] The contract ran through March 2011, but the two automakers extended the deal to keep the electric Roadster in production through December 2011 with a minimum number of 2,400 units,[37] when production ended,[needs update] mostly because of tooling changes orchestrated by one of its suppliers.[38] In June 2010, it was reported that Tesla sold a total of US$12.2 million zero emission vehicle credits to other automakers, including Honda, up to March 31, 2010.[39]
IPO and Model S

On January 29, 2010, Tesla Motors filed Form S-1 with the U.S. Securities and Exchange Commission,[40] as a preliminary prospectus indicating its intention to file an initial public offering (IPO) underwritten by Goldman Sachs, Morgan Stanley, J. P. Morgan, and Deutsche Bank Securities. On May 21, 2010, Tesla announced a "strategic partnership" with Toyota, which agreed to purchase US$50 million in Tesla common stock issued in a private placement[41][42] to close immediately after the IPO.[43] Executives at both companies said that they would cooperate on "the development of electric vehicles, parts, and production system and engineering support."[42] Less than two months later, Toyota and Tesla confirmed that their first platform collaboration would be to build an electric version of the RAV4 EV.[44] In October 2014, both Daimler and Toyota sold their holdings of Tesla shares[45][46] with a combined profit of over US$1 billion.[47]

On June 29, 2010, Tesla Motors launched its initial public offering on NASDAQ. 13,300,000 shares of common stock were issued to the public at a price of US$17.00 per share.[48] The IPO raised US$226 million for the company.[49] It was the first American car maker to go public since the Ford Motor Company had its IPO in 1956,[50] and by 2014 Tesla had market value half that of Ford.[51] In early 2013, Tesla had problems producing the Model S, and was running out of money. Musk proposed a US$11 billion deal with Google, but improved production and a sales push gave Tesla its first profitable quarter, and the deal was abandoned.[52][53][54]

During November 2013, following news of a third Model S fire, Tesla's stock fell more than 20 percent. All of those Model S fires had developed several minutes after the cars had struck significant road debris at high speeds and all of the vehicles had provided warnings to the occupants of serious battery damage, advising that an immediate stop was required. All three owners ordered new Model Ss. In the following months Tesla developed a battery protection system as a no-cost retrofit to all Model Ss.[55] No further regulatory action was taken, although there have been a few incidents since, most recently January 2016, with a Model S charging at a Norwegian Supercharger station.[56] Despite the drop in stock price, Tesla was still the top performer on the Nasdaq 100 index in 2013.[57] Tesla was seeking to sell 40,000 electric vehicles worldwide in 2014, adding China, Hong Kong, Japan, and Australia to the list of countries where it exports cars,[58] but in November 2014 Tesla reduced its guidance on sales down to 33,000 units for 2014.[59] As of 2014, Tesla has a US Corporate Average Fuel Economy (CAFE) of 276 mpg.[60]

Tesla makes its cars at the Tesla Factory in California. In October 2015, Tesla Motor announced the company was negotiating with the Chinese government on producing cars in China. Local production in China has the potential to reduce the sales prices of Tesla models by a third; however, foreign automakers are generally required to establish a joint venture with a Chinese company to produce cars domestically.[61] Elon Musk clarified at that time that production will remain in the U.S. in the foreseeable future, but if there's sufficient local demand for the Tesla Model 3 in China, a factory could be built in the country as soon as a year after the launch of the new model. Production in Europe will also depend on the region's demand for the Model 3.[62] Tesla was also considering building a manufacturing plant in India, according to Tesla's Chief Information Officer, Jay Vijayan. This would help Tesla to avoid 100% import duty which is applicable on import of CBU (Completely Built Unit) cars in India.[63] Tesla was also considering building a battery plant in India. "Given high local demand, a Gigafactory in India would probably make sense in the long term," Musk said in response to a specific question about whether he would consider a factory in India too.[64]

Tesla announced in November 2015 that during the third quarter of 2015 it produced a record 13,091 vehicles, and also revised its target sales for 2015 to between 50,000 and 52,000 vehicles, including both of its models available for retail sales. The company expects to achieve an average production and deliveries of 1,600 to 1,800 vehicles per week for Model S and Model X combined during 2016,[65][66] adding up to 80,000 to 90,000 new Model S and Model X vehicles in 2016.[67]
SolarCity acquisition

On August 1, 2016, Tesla agreed to acquire SolarCity Corp. for US$2.6 billion in stock. SolarCity was then the largest installer of rooftop solar systems in the United States.[68] More than 85% of unaffiliated Tesla and SolarCity shareholders voted to approve the acquisition,[69][70] which closed on November 21, 2016.[71]

After it acquired SolarCity, Tesla stopped using door to door sales tactics for solar systems; instead, it markets and sells its products at company showrooms. For a short time, Tesla partnered with Home Depot to sell solar and energy products through in store kiosks.[72] At the time, it did not provide a leasing option for solar panels, and consumers had to purchase them.[73]
Model 3 rollout
The Tesla Model 3 first deliveries event took place on July 28, 2017.

Model 3 was unveiled in March 2016. A week after the unveiling, global reservations totaled 325,000 units.[74][75] As a result of the demand for Model 3, in May 2016, Tesla advanced its 500,000 annual unit build plan (for all models) by two years to 2018.[76][77] This would in turn allow more Model 3 buyers to benefit from the full US$7,500 U.S. tax credit before the limit of 200,000 cars per maker since 2010 reduces the credit.[78][79]

On February 1, 2017 the company changed its name from Tesla Motors to Tesla.[80][81] In late March 2017, Tesla Inc. announced that Tencent Holdings Ltd., at the time China's "most valuable company," had purchased a 5% stake in Tesla for US$1.8 billion.[82][83] In 2017, Tesla surpassed Ford Motor Company and General Motors in market capitalization for a couple of months, making it the most valuable American automaker.[84][85] In June 2017, Tesla appeared for the first time in the Fortune 500 list.[84]

In the week preceding the debut on July 7, 2017, of the Model 3 sedan, Tesla's stock-market value declined by more than US$12 billion from a previous value of US$63 billion. The loss was a result of a combination of factors that disappointed investors. Demand for Tesla's existing luxury models, Model S and Model X, did not grow in the second quarter.[86] Brian Johnson of Barclays said that customer deposits for the Model S and Model X fell by US$50 million, potentially indicating that Tesla's introduction of the Model 3 could be adversely affecting their sales. Tesla predicted that luxury sales would reach 100,000 per year, below some analysts' expectations.[87]

Investors expressed concern about Tesla's plans for execution and its competitive risk, as Volvo Cars committed to introduce only electric and electric-assisted vehicles by 2019.[88][86] Johnson claimed that "Tesla will face intense competition by the next decade."[89]

Morningstar analyst David Whiston foresaw a revised, slower timetable for the Model 3 and a company acknowledgement of problems with building battery packs for its cars. In 2016 Musk predicted 100,000 Model 3 units would be sold in 2017, but that production may reach only 20,000 by December. Axel Schmidt, a managing director at consulting firm Accenture, said that Tesla's problems with Gigafactory 1 prove that increasing Model 3 production "remains a huge challenge".[89] In October 2017, Tesla reported delivery of 220 Model 3 cars, acknowledging this was "less than anticipated due to production bottlenecks".[90]

In early November 2017, Musk advised investors of a production delay that was primarily due to difficulties with the new battery that would allow Tesla to significantly reduce the manufacturing cost of the Model 3. The company was having difficulties with robots on the assembly line,[91] but the most serious issue was with one of the four zones in the battery manufacturing, caused by a "systems integration subcontractor", according to Musk.[92] "We had to rewrite all of the software from scratch for the battery module", he reported.[93] He assured investors that Tesla had "reallocated" top engineers to work on achieving a solution. By that time, Jon Wagner, director of battery engineering, had left the company.[94] Also in November, Musk postponed the target date for manufacturing 5000 of the vehicles per week from December 2017 to "sometime in March" 2018;[91] about which an analyst with Cowan and Company commented that "Elon Musk needs to stop over promising and under delivering".[95] On November 21, 2017, Bloomberg stated that "over the past 12 months, the electric-car maker has been burning money at a clip of about $8,000 a minute (or $480,000 an hour)" preparing for Model 3.[96]

In April 2018, Musk increased the 5000 per week number by 20%, forecasting Tesla could achieve 6,000 units per week by the end of June 2018.[97] When asked when the company would reach a production level of 10,000 units per week, he declined to speculate.[93]

For Q2 2018, Tesla reported delivery of 28,578 Model 3 vehicles, which exceeded combined Model S and X production (24,761), almost three times the amount of Model 3 vehicles in Q1.[98]

For Q3 2018, Tesla reported delivery of 55,840 Model 3 vehicles.[99]

For Q4 2018, Tesla reported delivery of 63,150 Model 3 vehicles.[100]
2018 consideration of taking Tesla private

In an August 7, 2018 tweet, major Tesla stockholder and Tesla CEO Elon Musk stated: "Am considering taking Tesla private at $420. Funding secured."[101][102] On Tesla's blog Musk elaborated that Tesla's status as a public company subjects it to the quarterly earnings cycle that puts enormous pressure on the company to make decisions that may be right for a given quarter, but not necessarily right for the company's long-term growth. Additionally, as the most shorted stock in the history of the stock market, being a publicly traded company means that there are large numbers of investors who may have the incentive to attack the company.[103] Musk released a considerably more detailed statement on the Tesla Blog the following week indicating that the proposal was by him in his personal capacity, and not as CEO of Tesla. Furthermore, he indicated that he had high confidence in the funding being secured based on discussions with the managing director of the Saudi sovereign wealth fund who had requested Musk consider taking Tesla private and indicated strong capital support for doing so.[104] On August 24, Musk released a statement indicating that both he and the Tesla Board of Directors had made the decision for the company to remain traded on the public stock markets.[105][106] In September 2018, Musk was sued by the U.S. Securities and Exchange Commission for the tweet claiming that funding had been secured for taking Tesla private. The lawsuit characterized the tweet as false, misleading, and damaging to investors, and sought to bar Musk from serving as CEO for publicly traded companies.[107][108] Musk settled with the SEC two days later. The settlement terms required Musk to step down as chairman, and prohibited him from running for chairman again for three years. Additionally, he and Tesla Inc. were fined US$20M each to reimburse investors who were harmed by Musk's tweet.[109][110]

In November 2018, Tesla vehicles outsold Mercedes-Benz in the United States market for the first time.[111]
Financials

Tesla has financed operations (production, development, administration, etc.) by sales income, stock offering and bond sales. In May 2013 Tesla raised US$1.02 billion (US$660 million from bonds) partially to repay the Department of Energy loans received from the ATVM loan program after their first profitable quarter.[112][113] In February 2014 Tesla raised US$2 billion from bonds to build the first GigaFactory.[113] In August 2015, Tesla raised US$738 million in stock to build the Model X.[114] In May 2016, Tesla raised US$1.46 billion in stock to build the Model 3.[115] By 2016, Tesla had raised over US$4.5 billion since its IPO in 2010.[116]

Tesla entered the Interbrand Top100 Best Global Brands in 2016 in position 100 with a brand valuation of US$4 billion.[117] On October 26, 2016, Tesla posted a profitable quarter, their first in 8 quarters, defying industry expectations.[118]

According to the Wall Street Journal, in September 2018, the company's stock fell to its lowest price in a year, around the time that CEO Elon Musk smoked marijuana during a live TV interview.[119]

As of April 2019, Musk owns about 38.5 million Tesla shares, which equates to about 21.7% of the company.[120]

On January 10, 2020, Tesla become the most valuable American automaker to ever exist, with a market capitalization of US$86 billion.[121] On January 29, 2020, Tesla became the world's second most valuable automaker, with a market capitalization of US$104 billion, passing Volkswagen's US$84 billion.[122] On July 1, 2020, Tesla reached a market capitalization of US$206 billion, surpassing Toyota's US$202 billion to become the world's largest automaker by market capitalization.[123]

Tesla issued US$2 billion of new shares on February 18, 2020.[124]

From July 2019 to June 2020, Tesla recorded four profitable quarters in a row for the first time, which made it eligible for inclusion in the S&P 500.[125] 
